version: '3'
services:
  mysql:
    container_name: mysql_${PJ_NAME}
    image: mysql:${MYSQL_VER}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    privileged: true
  phpmyadmin:
    container_name: phpmyadmin_${PJ_NAME}
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /sessions
    privileged: true
  php:
    container_name: web_${PJ_NAME}
    build: ${WEB_BUILD_DIR}
    image: ${WEB_IMAGE_NAME}
    ports:
      - ${WEB_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ${WEB_LOCAL_VOLUME_DIR1}:${WEB_CONTEAINER_VOLUME_DIR1}
      - ${WEB_LOCAL_VOLUME_DIR2}:${WEB_CONTEAINER_VOLUME_DIR2}
    privileged: true
volumes:
  db:
